.TH LIBSHA1_UNMARSHAL 3 2019-02-10 libsha1
.SH NAME
libsha1_unmarshal \- Unmarshal a SHA 1/0 hashing state
.SH SYNOPSIS
.nf
#include <libsha1.h>

size_t libsha1_unmarshal(struct libsha1_state *restrict \fIstate\fP, const void *restrict \fIbuf\fP, size_t \fIbufsize\fP);
.fi
.PP
Link with
.IR \-lsha1 .
.SH DESCRIPTION
The
.BR libsha1_unmarshal ()
function unmarshal
.I state
from the buffer
.IR buf .
.I bufsize
shall be the maximum number of bytes the
function may read from
.IR buf .
.SH RETURN VALUE
The
.BR libsha1_unmarshal ()
function returns the number of unmarshalled
bytes (this number is always positive) upon
successful completion, otherwise 0 is returned.
.SH ERRORS
The
.BR libsha1_unmarshal ()
function will fail if:
.TP
.B EINVAL
.I bufsize
is too small or the contents of
.I buf
is invalid or created with an incompatible
version of the library.
.SH EXAMPLES
None.
.SH APPLICATION USAGE
None.
.SH RATIONALE
None.
.SH FUTURE DIRECTIONS
None.
.SH NOTES
None.
.SH BUGS
None.
.SH SEE ALSO
.BR libsha1_marshal (3)
